Repository WildCodeSchool/orleans-0918-php-javapop, pull requests merged in 2018-10, with the labels that each got.

#1 Template
  .gitignore
  public/assets/css/agency.css
  public/assets/css/agency.min.css
  public/assets/css/navBar.css
  public/assets/css/style.css
  public/assets/css/styles.css
  public/assets/images/about/1.jpg
  public/assets/images/about/2.jpg
  public/assets/images/about/3.jpg
  public/assets/images/about/5.jpg
  public/assets/images/about/6.jpg
  public/assets/images/about/7.jpg
  public/assets/images/about/8.jpg
  public/assets/images/img-bg/carteboissons-bg.jpg
  public/assets/images/img-bg/evenements.jpeg
  public/assets/images/img-bg/evenements2.jpeg
  public/assets/images/img-bg/grey.jpg
  public/assets/images/img-bg/header-bg.jpg
  public/assets/images/img-bg/nous-trouver-bg.jpg
  public/assets/images/img-bg/photos-bg.jpg
  public/assets/images/logos/java-pop-live.png
  public/assets/images/logos/logo_javapop.png
  public/index.php
  src/View/Item/index.html.twig
  src/View/layout.html.twig
  src/View/navbar.html.twig
Labels: reviewed by po

#2 layout propre et fonctionnnel
  src/View/layout.html.twig
Labels: correction done, reviewed by po

#3 Dev
  .gitignore
  public/assets/css/agency.css
  public/assets/css/agency.min.css
  public/assets/css/navBar.css
  public/assets/css/style.css
  public/assets/css/styles.css
  public/assets/images/about/1.jpg
  public/assets/images/about/2.jpg
  public/assets/images/about/3.jpg
  public/assets/images/about/5.jpg
  public/assets/images/about/6.jpg
  public/assets/images/about/7.jpg
  public/assets/images/about/8.jpg
  public/assets/images/img-bg/carteboissons-bg.jpg
  public/assets/images/img-bg/evenements.jpeg
  public/assets/images/img-bg/evenements2.jpeg
  public/assets/images/img-bg/grey.jpg
  public/assets/images/img-bg/header-bg.jpg
  public/assets/images/img-bg/nous-trouver-bg.jpg
  public/assets/images/img-bg/photos-bg.jpg
  public/assets/images/logos/java-pop-live.png
  public/assets/images/logos/logo_javapop.png
  public/index.php
  src/View/Item/index.html.twig
  src/View/layout.html.twig
  src/View/navbar.html.twig
Labels: reviewed by po

#25 Sprint1 us14
  app/routing.php
  public/assets/css/agency.css
  public/assets/css/style.css
  public/assets/images/about/0.jpg
  public/assets/images/about/4.jpg
  src/Controller/EventController.php
  src/Model/AbstractManager.php
  src/Model/Event.php
  src/Model/EventManager.php
  src/View/Event/index.html.twig
  src/View/layout.html.twig
Labels: changes requested

#66 Dev
  app/routing.php
  public/assets/css/agency.css
  public/assets/css/style.css
  public/assets/images/about/0.jpg
  public/assets/images/about/4.jpg
  src/Controller/EventController.php
  src/Model/AbstractManager.php
  src/Model/Event.php
  src/Model/EventManager.php
  src/View/Event/index.html.twig
  src/View/layout.html.twig
Labels: reviewed by po

#75 Dev
  app/routing.php
  public/assets/css/style.css
  public/assets/images/img-bg/localisation-bg.jpg
  src/Controller/LocationController.php
  src/View/Location/index.html.twig
Labels: reviewed by po

#63 Sprint2 us 17
  app/routing.php
  public/assets/css/style.css
  public/assets/images/img-bg/artistes-bg.jpg
  public/assets/images/img-bg/carte-bg.jpg
  public/assets/images/img-bg/contact-bg.jpg
  public/assets/images/img-bg/evenement-bg.jpg
  public/assets/images/img-bg/photos-bg.jpg
  public/assets/images/img-bg/photos.jpg
  src/Controller/AdminController.php
  src/Model/Item.php
  src/View/Admin/index.html.twig
  src/View/navbar.html.twig
Labels: changes requested

#76 Dev
  app/routing.php
  public/assets/css/style.css
  public/assets/images/img-bg/artistes-bg.jpg
  public/assets/images/img-bg/carte-bg.jpg
  public/assets/images/img-bg/contact-bg.jpg
  public/assets/images/img-bg/evenement-bg.jpg
  public/assets/images/img-bg/photos-bg.jpg
  public/assets/images/img-bg/photos.jpg
  src/Controller/AdminController.php
  src/Model/Item.php
  src/View/Admin/index.html.twig
  src/View/navbar.html.twig
Labels: reviewed by po

#70 Sprint2 US1
  app/routing.php
  public/assets/css/agency.min.css
  public/assets/css/style.css
  public/assets/images/logos/javapop-live.png
  src/Controller/HomeController.php
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: correction done, reviewed by po

#78 Dev
  app/routing.php
  public/assets/css/agency.min.css
  public/assets/css/style.css
  public/assets/images/logos/javapop-live.png
  src/Controller/HomeController.php
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: reviewed by po

#81 Sprint3 us9 gallery view
  .gitignore
  app/routing.php
  public/assets/css/style.css
  public/assets/images/gallery/.gitkeep
  src/Controller/GalleryController.php
  src/Model/Picture.php
  src/Model/PictureManager.php
  src/View/Gallery/index.html.twig
Labels: reviewed by po

#83 Dev
  .gitignore
  app/routing.php
  public/assets/css/style.css
  public/assets/images/gallery/.gitkeep
  src/Controller/GalleryController.php
  src/Model/Picture.php
  src/Model/PictureManager.php
  src/View/Gallery/index.html.twig
Labels: reviewed by po

#79 Sprint2 us08
  app/routing.php
  public/assets/css/card.css
  public/assets/css/style.css
  src/Controller/AbstractController.php
  src/Controller/DrinkController.php
  src/Model/AbstractManager.php
  src/Model/Drink.php
  src/Model/DrinkManager.php
  src/View/Drink/index.html.twig
  src/View/Item/index.html.twig
  src/View/layout.html.twig
Labels: reviewed by po

#86 Dev to Master
  app/routing.php
  public/assets/css/card.css
  public/assets/css/style.css
  src/Controller/AbstractController.php
  src/Controller/DrinkController.php
  src/Model/AbstractManager.php
  src/Model/Drink.php
  src/Model/DrinkManager.php
  src/View/Drink/index.html.twig
  src/View/Item/index.html.twig
  src/View/layout.html.twig
Labels: reviewed by po

#88 sprint4_US28_admin boissons
  app/routing.php
  src/Controller/DrinkAdminController.php
  src/View/DrinkAdmin/index.html.twig
Labels: reviewed by po

#90 Dev
  app/routing.php
  src/Controller/DrinkAdminController.php
  src/View/DrinkAdmin/index.html.twig
Labels: reviewed by po

#85 Sprint3 us26
  app/routing.php
  src/Controller/EventAdminController.php
  src/View/Admin/index.html.twig
  src/View/EventAdmin/index.html.twig
Labels: reviewed by po
